---
title: "Sankey Diagram"
output: html_document
date: '2022-10-21'
---

```{r setup}
setwd("C:/Extent Map proj")

library(tidyverse)
library(viridis)
library(patchwork)
library(hrbrthemes)
library(circlize)
library(networkD3)
library(htmlwidgets)
```


# Load dataset

```{r}
data <- read.csv("mhi_chge_matrix_0414.csv", header = TRUE)    # need to manually edit csv format so as to have 7x7 table
```

# I need a long format

```{r}
data_long <- data %>%
  rownames_to_column %>%
  gather(key = 'key', value = 'value', -rowname) %>%
  filter(value > 0)
colnames(data_long) <- c("source", "target", "value")
data_long$target <- paste(data_long$target, " ", sep="")
```


# From these flows we need to create a node data frame: it lists every entities involved in the flow

```{r}
nodes <- data.frame(name=c(as.character(data_long$source), as.character(data_long$target)) %>% unique())
```

# With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.

```{r}
data_long$IDsource=match(data_long$source, nodes$name)-1 
data_long$IDtarget=match(data_long$target, nodes$name)-1
```


# prepare colour scale

```{r}
ColourScal ='d3.scaleOrdinal() .range(["#FDE725FF","#B4DE2CFF","#6DCD59FF","#35B779FF","#1F9E89FF","#26828EFF","#31688EFF","#3E4A89FF","#482878FF","#440154FF"])'
```


# Make the Network

```{r}
p = sankeyNetwork(Links = data_long, Nodes = nodes,
                     Source = "IDsource", Target = "IDtarget",
                     Value = "value", NodeID = "name", 
                     sinksRight=FALSE, colourScale=ColourScal, nodeWidth=40, fontSize=13, nodePadding=20)
p
```
```{r}

saveWidget(p, file= "mhi_sankey0414.html")
```

